homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Prague
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation

frontend:

http:
  api_password: !secret http_password
  
updater:

discovery:

conversation:

history:

logbook:

logger:
  default: info

config:

sun:

ios:

zone: !include_dir_list zones/
climate: !include_dir_list climate/
weather: !include_dir_list weather/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
shell_command: !include misc/shell_commands.yaml
camera: !include_dir_list cameras/
group: !include_dir_merge_named groups/
media_player:
  - platform: samsungtv
    host: !secret samsung_ip
    name: Samsung Smart TV Living Room
  - platform: plex
  - platform: apple_tv
    host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id
    start_off: true

automation:
  - alias: 'Update Available Notifications'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.notify
      data:
        message: 'Update for Home Assistant is available.'
