homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Prague
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

frontend:

http:
  api_password: !secret http_password
  
updater:

discovery:

conversation:

history:

logbook:

logger:
  default: warning
  logs:
#    homeassistant.components.homekit: debug
    homeassistant.components.climate: debug
    custom_components.climate.cometblue: debug
    cometblue.device: debug
#    pyhap: debug

config:

sun:

map:

#mqtt:
#  broker: !secret mqtt_ip

ios:

zone: !include_dir_list zones/
climate: !include_dir_list climate/
weather: !include_dir_list weather/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
shell_command: !include misc/shell_commands.yaml
camera: !include_dir_list cameras/
group: !include_dir_merge_named groups/
media_player: !include_dir_list media/
homekit: !include homekit/homekit.yaml
automation: !include_dir_merge_list automation/
